### ISSUE TITLE
Implement CLI library

### ISSUE THREAD

**Issue by RolandWarburton** [AstroStreakNet/streak#1]
Currently @karshPrime  has written a simple menu for the CLI software using the standard library [flag](https://pkg.go.dev/flag).

![image](https://github.com/AstroStreakNet/streakcli/assets/36120361/6b560249-5408-48f4-8417-f8d0dc05cfbf)

We could now consider how to further development of the CLI flag system to handle more complex use cases.

There are some popular CLI libraries that i would suggest exploring and deciding if they are required.

[cli](https://cli.urfave.org/) is something i have used in the past. Its rather simple to use.

[cobra](https://cobra.dev/) is something i have attempted to use but i usually go with urfave/cli in most use cases. Cobra is able to handle more complex use cases at the cost of additional learning curve.

**Comment by karnull** [comment]
Cobra does seem to be the perfect fit for this. Initially, I was just settings on flags with default values and letting users overwrite them with inline args (or config defaults). It was kinda like a duct-tape solution for the problem, but yeah, as the project grows more complex, using this lib would be hecka beneficial.

**Comment by karshPrime** [comment]
didn't mean to close it yet...
